Blood_bank/blood_bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('', include('booking.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blood_bank/booking/urls.py
from django.urls import path
from .import views
app_name='booking'
urlpatterns=[
    path('',views.home,name='home'),
    path('donor_register/',views.donor_register,name="donor_register")
]

Blood_bank/login/urls.py
from . import views
from django . urls import path
app_name='login'
urlpatterns=[
    path('',views.login,name="login"),
    path('user_login/',views.user_page,name="user_page"),
    path('register/',views.register,name="register"),
    path('logout/',views.logout,name="logout"),
]

Blood_bank/booking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
class District_tb(models.Model):
    district=models.CharField(max_length=25,blank=True,unique=True)
    slug = models.SlugField(max_length=252, unique=True)
    def __str__(self):
        return '{}'.format(self.district)

class Centers_tb(models.Model):
    district=models.CharField(max_length=25,blank=True)
    center=models.CharField(max_length=35,blank=True,unique=True)

    def __str__(self):
        return '{}'.format(self.center)

class Donors_tb(models.Model):
    district=models.CharField(max_length=22,blank=True)
    name=models.CharField(max_length=20,blank=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    age=models.IntegerField(blank=True)
    gender=models.CharField(max_length=8,blank=True)
    blood_group=models.CharField(max_length=6,blank=True)
    address=models.TextField(max_length=50,blank=True)
    mail_id=models.EmailField(max_length=25,blank=True)
    phone_no=models.IntegerField(blank=True)
    center=models.CharField(max_length=20,blank=True)

Blood_bank/login/models.py
# from django.db import models
#
# class Credentials(models.Model):
#     user_name=models.CharField(max_length=15,blank=True,unique=True)
#     password=models.CharField(max_length=100,blank=True)

Blood_bank/booking/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from.models import Donors_tb,Centers_tb,District_tb
from django.contrib.auth.models import User

def home(request):
    return render(request,"home.html")
def donor_register(request):
    if request.method== "POST":
        name = request.user.username
        if User.objects.filter(username=name):
            username=User.objects.get(username=name)
        fullname=request.POST['fullname']
        gender=request.POST['gender']
        age=request.POST['age']
        ph_no=request.POST['ph_no']
        address=request.POST['address']
        email=request.POST['email']
        district=request.POST['district']

        #center=request.POST['center']
        blood_group=request.POST['blood_group']
        details=Donors_tb(username=username,age=age,phone_no=ph_no,blood_group=blood_group,address=address,mail_id=email,gender=gender,center="Ernakulam",district=district,name=fullname)
        details.save()
        if Donors_tb.objects.filter(username=username).exists():
            messages.info(request,"Registerd successfully")
        else:
            messages.info(request,"Registration failed")
    district=District_tb.objects.all()
    centers=Centers_tb.objects.all()
    user_auth = request.user.username
    if user_auth != None:
        return render(request,"donor_regsiter_page.html",{'district':district,'centers':centers})

Blood_bank/login/views.py
from django.contrib import messages, auth
from django.shortcuts import render, redirect
from django.contrib.auth.models import User


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        conpassword = request.POST['conpassword']

        if (password == conpassword):
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already exits")
                return redirect('login:register')
            else:
                new_user = User.objects.create_user(username=username,password=password)
                new_user.save()
                return redirect('login:login')
        else:
            messages.info(request, "Password not matching")
            return redirect('login:register')
    return render(request,"register.html")


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('login:user_page')
        else:
            messages.info(request,"Invalid username or password")
            return redirect('login:login')
    return render(request,"login_page.html")

def logout(request):
    auth.logout(request)
    return redirect('booking:home')

def user_page(request):
    return render(request,"User_Page.html")

Blood_bank/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block matadescription %}{% endblock %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
     <link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<div class="container-fluid">
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
 </div>
</body>
</html>

Blood_bank/templates/Home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Blood bank
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="home_bgimg" >
<a href="https://en.wikipedia.org/wiki/Blood_donation" class="btn btn-success btn-lg" id="advantage_btn">Know more</a>
</div>
</div>
{% endblock %}

Blood_bank/templates/User_Page.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}
Blood Bank
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="userbg">
<a class="btn btn-success btn-lg" href="{% url 'booking:donor_register' %}" id="dregbtn">Donate blood</a>
    </div>
</div>
{% endblock %}

Blood_bank/templates/donor_regsiter_page.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}
Donor Registration
{% endblock %}
{% block content %}

    <script>
		$(document).ready(function()
		{
		  var $productvar=$("#districtbox");
		  $itemvar=$(#centerbox");
		  $options=$itemvar.find('option');
		  $productvar.on('change'.function()
		  {
		     $item.html()($options.filter('[value="'+this.value+'"]'))
		  }).trigger('change');
	</script>
<div class="container-fluid">
 <div class="bgimg">
{% for msg in messages %}
     <h2><p>{{msg}}</p></h2>
{% endfor %}
<form action="{% url 'booking:donor_register' %}" method="post">
    {% csrf_token %}
<table class="regtb">
    <tr>
        <th colspan="2" align="center">
            <h2>Registration Page</h2>
        </th>
    </tr>
 <tr>
     <td>
         <label>Full name</label>
     </td>
     <td><input type="text" name="fullname" placeholder="Enter your fullname"></td><br>
 </tr>

 <tr>
     <td>
         <label>Age</label>
     </td>
     <td>
         <input type="number" name="age" placeholder="Enter your age">
     </td>
 </tr>
 <tr>
     <td>
         <label>Gender</label>
     </td>
     <td>
        <input type="radio" name="gender" value="Male">
         <label>Male</label>
        <input type="radio" name="gender" value="Female">
        <label>Female</label>
     </td>
 </tr>
 <tr>
     <td>
         <label>Phone number</label>
     </td>
     <td>
         <input type="number" name="ph_no" placeholder="Phone number">
     </td>
 </tr>
 <tr>
     <td>
         <label>Address</label>
     </td>
     <td>
         <input type="text" name="address" placeholder="Address">
     </td>
 </tr>
  <tr>
     <td>
         <label>Email id</label>
     </td>
     <td>
         <input type="email" name="email" placeholder="email">
     </td>
 </tr>
  <tr>
     <td>
         <label>Blood_group</label>
     </td>
     <td>
         <input type="text" name="blood_group" placeholder="Blood group">
     </td>
 </tr>
<tr>
    <td>
        <label>Choose your District</label>
    </td>
    <td>
        <select name="district" id="districtbox" onchange="myFunction()">
            <option value="" selected></option>
            {% for d in district %}
            <option value="{{d.district}}">{{d.district}}</option>
            {% endfor %}
        </select>
        <script>
            fuction myFunction(){
            var x=document.getElementById("districtbox").value;
            }
        </script>
    </td>
</tr>
<tr>
    <td>
       <label>Center</label>
    </td>
    <td>
        <select name="center" id="centerbox">
         <option value="" selected></option>
       {% for i in centers %}
            <option value="{{i.center}}">{{i.center}}</option>
        {% endfor %}
        </select>
    </td>
</tr>
    <div on=""></div>
    <tr>
        <td colspan="2" align="center">
            <input class="btn btn-success" type="submit" value="Register">
        </td>
    </tr>
</table>
</form>
 </div>
</div>
{% endblock %}

Blood_bank/templates/login_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Login Page
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="reg_bgimg">
<section>
<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Have an account?</h3>
						    {% for msg in messages %}
						<div style="color:red">*{{msg}}</div>
                            {% endfor %}
		      	<form action="{% url 'login:login' %}" method="post" class="signin-form">
					{% csrf_token %}
		      		<div class="form-group" style="padding-top: 6px;">
		      			<input type="text" class="form-control" placeholder="username" name=username required="">
		      		</div>

	            <div class="form-group" style="padding-top: 6px;">
	              <input type="password" class="form-control" placeholder="password" name="password" required="" style="background-color: transparent;">
	            </div>
	            <div class="form-group" style="padding-top: 6px;">
	            	<button type="submit" class="form-control btn btn-primary">Sign In</button>
	            </div>
	          </form>

		      </div>
				</div>
			</div>
		</div>
	</section>
</div>
	</div>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

Blood_bank/templates/navbar.html
<div class="container-fluid">
<nav class="navbar navbar-expand-lg" style="height: 3rem;margin-top: .5rem;width: 100%;">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapsez" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item" style="margin-left: 2px;">
          <a role="button" class="btn btn-danger btn-lg" href="{% url 'booking:home' %}">Home</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated%}
          <a role="button" class="btn btn-danger btn-lg" href="{% url 'booking:donor_register' %}">Donor Register</a>
          {% else %}
          <a role="button" class="btn btn-danger btn-lg" href="{% url 'login:register' %}">Register</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
              <a role="button" class="btn btn-danger btn-lg" href="{% url 'login:logout' %}">Logout</a>
          {% else %}
              <a role="button" class="btn btn-danger btn-lg" href="{% url 'login:login' %}">Login</a>
          {% endif %}
        </li>
          <li class="nav-item dropdown">
          <a class="btn btn-danger btn-lg" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Districts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for d in links %}
            <li><a class="dropdown-item" href="{{d.slug}}">{{d.district}}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
    </div>
</nav>
</div>

Blood_bank/templates/register.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
	<div class="reg_bgimg">
		{% for msg in messages %}
            {{msg}}
            {% endfor %}
				<form action="{% url 'login:register' %}" method="post">
					{% csrf_token %}
					<table class="regtb">
                    <tr>
						<th colspan="2"><h2>CREATE YOUR ACCOUNT</h2></th>
					</tr>
						<tr>
							<td>
								<label>Username</label>
							</td>
							<td>
								<input class="text" type="text" name="username" placeholder="Username" required="">
							</td>
						</tr>
						<tr>
							<td>
								<label>Password</label>
							</td>
							<td>
								<input class="mregpass" type="password" name="password" placeholder="Password" required="">
							</td>
						</tr>
						<tr>
							<td>
								<label>Confirm password</label>
							</td>
							<td>
							<input class="mregpass" type="password" name="conpassword" placeholder="Confirm Password" required="">
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input type="submit" value="SIGNUP">
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
  				                 <p>Have an Account? <a href="{% url 'login:login' %}"> Login Now!</a></p>
							</td>
						</tr>
					</table>
				</form>
	</div>
</div>
{% endblock %}